name: mysub
description: A habit tracker built for couples.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.1.0 <5.0.0"
  flutter: ">=3.1.0 < 5.0.0"
dependencies:
  awesome_notifications: ^0.10.0
  cloud_firestore: ^5.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^5.0.0
  firebase_core: ^3.0.0
  firebase_messaging: ^15.1.4
  firebase_storage: ^12.0.0
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.5
  flutter_launcher_icons: ^0.14.0
  flutter_local_notifications: ^18.0.1
  flutter_native_splash: ^2.2.6
  flutter_quill: ^10.8.5
  flutter_riverpod: any
  flutter_spinkit: ^5.1.0
  flutter_svg: ^2.0.10+1
  fpdart: ^1.1.0
  get_it: ^7.2.0
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.1.1
  image_picker: ^1.1.1
  intl: any
  intl_phone_field: ^3.1.0
  logger: ^2.3.0
  lottie: ^3.1.2
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.1.6
  uuid: ^4.4.0
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.0.1
  mockingjay: ^0.6.0
  mocktail: ^1.0.3

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/animations/
    - assets/svg/
    - assets/images/navbar/
    - assets/images/settings/

flutter_native_splash:
  color: "ffffff"

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/images/mysub-logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: false
    image_path: "path/to/image.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
  windows:
    generate: false
    image_path: "path/to/image.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: false
    image_path: "path/to/image.png"
